Improve documentation
wmde/banner-screenshots pull request #454
Opened 2022-10-13 17:18 UTC by gbirke

The README now documents the development environment, how to create
screenshots is now described in `PRODUCTION.md`

Change Makefile to delete the `amqp.test` container when it's stopped. This
will avoid errors after rebooting your computer.

Ticket: https://phabricator.wikimedia.org/T320747

2022-11-01 07:06 UTC, Abban approved these changes

2022-11-01 07:07 UTC, Abban commented
I think when we improve the banner development environment with the extra links we should put a little update in on naming the branches in test channels?

2022-11-01 15:21 UTC, gbirke commented
> I think when we improve the banner development environment with the extra links we should put a little update in on naming the branches in test channels?

I don't know where you want to put the updated documentation and what you want to update.

I think it's a good convention to name the branches after the campaigns because it's consistent, but the only place where it's relevant is for the CLI tool, because it downloads the campaign config from that branch and tries to determine the channel from the branch name. That's what I wanted to document here.

Or are you thinking about linking to the PR from the dev environment start page? Then the documentation for that convention should be somewhere else than in the screenshot one.

2022-11-11 16:12 UTC, moiikana requested changes

2022-11-11 16:12 UTC, moiikana commented on README.md
> +	docker stop amqp.test
have to rename the container here as well, like in the makefile
```suggestion
	docker stop banner-screenshots-rabbitmq
```

2023-01-11 12:43 UTC, moiikana approved these changes

2023-01-11 13:32 UTC, merged